name: New Code Freeze
on:
    release:
        types: [released]

permissions: {}

env:
    GIT_COMMITTER_NAME: 'WooCommerce Bot'
    GIT_COMMITTER_EMAIL: 'no-reply@woocommerce.com'
    GIT_AUTHOR_NAME: 'WooCommerce Bot'
    GIT_AUTHOR_EMAIL: 'no-reply@woocommerce.com'

jobs:
    verify-release:
        name: 'Verify if the release is a major version release, that ends with .0'
        runs-on: ubuntu-20.04
        outputs:
            run: ${{ steps.verify.outputs.run }}
        steps:
            - name: Verify release
              id: verify
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;
                      const release = event.release;

                      if (release.tag_name.endsWith('.0')) {
                          core.setOutput('run', 'true');
                      } else {
                          core.setOutput('run', 'false');
                      }

            - name: Verify if any PR is left open by author:app/github-actions
              id: verify-prs
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      const prs = await github.rest.pulls.list({ owner, repo, state: 'open', author: 'app/github-actions' });
                      if (prs.data.length > 0) {
                          core.setOutput('prs-left-open-count', prs.data.length);
                          core.setFailed(`Found ${prs.data.length} open PRs from github-actions bot. Please close them before proceeding.`);
                      }

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze workflow failed.
                      :warning-8c: There are `${{ steps.verify-prs.outputs.prs-left-open-count }}` PRs left open by `app/github-actions` bot. Please merge them and re-run the workflow. Merging them is essential to maintain the integrity of code across all branches. Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
    prep-for-code-freeze:
        name: 'Prepare for code freeze - generate next release branch and milestone'
        if: needs.verify-release.outputs.run == 'true'
        needs: verify-release
        runs-on: ubuntu-20.04
        outputs:
            nextReleaseBranch: ${{ steps.extract-version.outputs.nextReleaseBranch }}
            nextMajorMilestone: ${{ steps.extract-version.outputs.nextMajorMilestone }}
        steps:
            - name: Extract version from release tag
              id: extract-version
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;
                      const currentTag = event.release.tag_name;
                      const [major, minor, patch] = currentTag.split('.').map(Number);

                      let nextMajor = major;
                      let nextMinor = minor + 1;
                      if (nextMinor > 9) {
                          nextMajor += 1;
                          nextMinor = 0;
                      }

                      const nextReleaseBranch = `release/${nextMajor}.${nextMinor}`;
                      const nextMajorMilestone = `${nextMajor}.${nextMinor}.0`;
                      core.setOutput('nextReleaseBranch', nextReleaseBranch);
                      core.setOutput('nextMajorMilestone', nextMajorMilestone);
                      console.log(`Next release branch: ${nextReleaseBranch}`);
                      console.log(`Next milestone: ${nextMajorMilestone}`);
    
    create-code-freeze-branch-and-milestone:
        name: 'Create the code freeze branch and milestone for next release'
        needs: prep-for-code-freeze
        runs-on: ubuntu-20.04
        permissions:
          issues: write
          contents: write
        steps:
            - name: Fetch all the branches
              uses: actions/checkout@v3
              with:
                ref: trunk

            - name: Create code freeze branch out of trunk
              run: |
                  git checkout trunk
                  git checkout -b $RELEASE_BRANCH
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Push the new branch to the remote repository
              run: git push origin $RELEASE_BRANCH
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Create milestone in Github repository
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      await github.rest.issues.createMilestone({
                          owner: owner,
                          repo: repo,
                          title: process.env.MILESTONE
                      });
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MILESTONE: ${{ needs.prep-for-code-freeze.outputs.nextMajorMilestone }}

            - name: Notify Slack on success
              if: ${{ success() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze completed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}` :checking:
                      You can raise a code freeze exception if you need something to be included in this release, see the <${{ secrets.FG_LINK }}/code-freeze-for-woocommerce-core-release|fieldguide page for the code freeze>.
                  slack-optional-unfurl_links: false
                  slack-optional-unfurl_media: false

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :warning-8c: Code freeze failed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}`. Please check the logs for more details. Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    changelog-version-update-for-trunk-and-next-release:
        name: Update changelog and version for trunk and next release
        runs-on: ubuntu-20.04
        needs: [create-code-freeze-branch-and-milestone, prep-for-code-freeze]
        permissions:
          contents: write
          pull-requests: write
        steps:
            - uses: actions/checkout@v3

            - name: Git fetch trunk branch
              run: git fetch origin trunk

            - name: Git fetch next release branch
              run: git fetch origin ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Copy readme.txt to vm root
              run: cp ./plugins/woocommerce/readme.txt ../../readme.txt

            - name: Switch to trunk branch
              run: git checkout trunk

            - name: Create a new branch based on trunk
              run: git checkout -b prep/post-release-tasks-${{ github.event.release.tag_name }}

            - name: Check if we need to continue processing
              uses: actions/github-script@v6
              id: check
              with:
                  script: |
                      const fs = require( 'node:fs' );
                      const version = context.payload.release.tag_name;

                      fs.readFile( './plugins/woocommerce/readme.txt', 'utf-8', function( err, data ) {
                        if ( err ) {
                          console.error( err );
                        }

                        const regex = /Stable\stag:\s(\d+\.\d+\.\d+)/;

                        const stableVersion = data.match( regex )[1];

                        // If the release version is less than stable version we can bail.
                        if ( version.localeCompare( stableVersion, undefined, { numeric: true, sensitivity: 'base' } ) == -1 ) {
                          console.log( 'Release version is less than stable version. No automated action taken. A manual process is required.' );
                          core.setOutput( 'continue', 'false' )
                          return;
                        } else {
                          core.setOutput( 'continue', 'true' )
                        }
                      } )

            - name: Update changelog.txt entries
              uses: actions/github-script@v6
              id: update-entries
              if: steps.check.outputs.continue == 'true'
              with:
                  script: |
                      const fs = require( 'node:fs' );
                      const version = context.payload.release.tag_name;

                      // Read the saved readme.txt file from earlier.
                      fs.readFile( '../../readme.txt', 'utf-8', function( err, readme ) {
                        if ( err ) {
                          core.setFailed( err );
                        }

                        const regex = /(== Changelog ==[\s\S]+)\s{2}\[See changelog for all versions\]\(https:\/\/raw\.githubusercontent\.com\/woocommerce\/woocommerce\/trunk\/changelog\.txt\)\./;

                        const entries = readme.match( regex )[1];

                        fs.readFile( './changelog.txt', 'utf-8', function( err, changelog ) {
                          if ( err ) {
                            core.setFailed( err );
                          }

                          const regex = /== Changelog ==/;

                          const updatedChangelog = changelog.replace( regex, entries );

                          fs.writeFile( './changelog.txt', updatedChangelog, err => {
                            if ( err ) {
                              core.setFailed( err );
                            }
                          } )
                        } )
                      } )

            - name: Commit changes
              id: commit-changes
              run: |
                git commit -am "Prep post release ${{ github.event.release.tag_name }}"
                commit_sha=$(git rev-parse HEAD)
                echo "::set-output name=commit_hash::${commit_sha}"

            - name: Push branch up
              run: git push origin prep/post-release-tasks-${{ github.event.release.tag_name }}

            - name: Switch to next release branch
              run: git checkout ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Cherry pick commit to next release branch
              run: git cherry-pick ${{ steps.commit-changes.outputs.commit_hash }}

            - name: Push next release branch up
              run: git push origin ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Create the PR
              uses: actions/github-script@v6
              with:
                  script: |
                      const body = "This PR updates the changelog.txt entries based on the latest release: ${{ github.event.release.tag_name }}"

                      const pr = await github.rest.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: "Update changelog.txt from release ${{ github.event.release.tag_name }}",
                        head: "prep/post-release-tasks-${{ github.event.release.tag_name }}",
                        base: "trunk",
                        body: body
                      })

                      const prCreated = await github.rest.pulls.requestReviewers({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.data.number,
                        reviewers: ["${{ github.event.release.author.login }}"]
                      })
